### ISSUE TITLE
PHP errors in theme/plugin editor are hidden

### ISSUE THREAD

**Issue by ajoah** [Pierre-Lannoy/wp-mailarchiver#2] opened 2021-01-22 17:49 UTC
**Describe the bug**
When the plugin is active, no more php error is displayed or logged in php error log file

**To Reproduce**
1. make an error anywhere with WP_DEBUG to true : (`fakeFunction();` for example)
2. The error is displayed
3. Install and activate the plugin
4. the error disappears

**Environment (please complete the following information):**
 - PHP version: 7.4
 - WordPress version : 5.6

**Comment by Pierre-Lannoy** [comment] 2021-01-22 18:08
Hi @ajoah !
Could you tell me where it should be displayed: on the frontend (if so, what's the `WP_DEBUG_DISPLAY` value?) or in a log file (if so, what's the `WP_DEBUG_LOG` value?)?
If you're on WP 5.5+ stack, what is your environment type ('local', 'development', 'staging' or 'production')?
Are you using loggers (like DecaLog)?

Thanks for you answers too help me to reproduce it.

**Comment by ajoah** [comment] 2021-01-23 09:00
Hi @Pierre-Lannoy,
Environment is on development
Decalog is not installed.

I made a demonstration on fresh WP install (from : https://jurassic.ninja/)

![demo-mailarchiver](https://user-images.githubusercontent.com/10757301/105573976-9c465d00-5d61-11eb-9499-9d7ffcb4d87a.gif)

**Comment by Pierre-Lannoy** [comment] 2021-01-27 13:12
Hi!
Aha. You're right but... it's worst than that: it's because the "standard" PHP error handler is overridden in the MailArchiver watchdog.
This is clearly a f**ing flaw.

I will try to fix it in the next release.
Thank you so much for this report...

**Comment by Pierre-Lannoy** [comment] 2021-02-24 00:17
Fix released in [2.2.0](https://github.com/Pierre-Lannoy/wp-mailarchiver/releases/tag/2.2.0).

**Closed as completed by Pierre-Lannoy** 2021-02-24 00:17 UTC
Labels: bug, good first issue
